In [10]:
import pandas as pd
import datetime as dt
from datetime import datetime, timedelta


#!pip install openpyxl

df=pd.read_excel('transit.xlsx')
date_format = "%y-%m-%d"
df['Date']=pd.to_datetime(df['Date'],format=date_format)
df['Weekday']=df['Date'].dt.day_name()
df.fillna({'One':'one','Two':'iOPEX','Three':'Three','Add':0,'Minus':0, 'yt':0, 'sleep_12':1, 'wake_8':0, 'screen':0, 'Number':95},inplace=True)

# BALANCE

In [11]:
current_balance=18000
current_date='24-11-18'
df_=df[df.Date<=pd.to_datetime(current_date)]
print(f'CURRENT BALANCE =======> {current_balance+df_.Add.sum()-df_.Minus.sum()}')

CURRENT BALANCE =======> 18000

# WEIGHT

In [12]:
current_weight = 95
current_date = '24-11-18'
current_date = pd.to_datetime(current_date, format='%y-%m-%d')
days_difference = (dt.datetime.today().date() - current_date.date()).days
expected_weight = current_weight - 0.5 * days_difference/7
print(f'EXPECTED WEIGHT =======> {expected_weight:.2f}')

EXPECTED WEIGHT =======> 95.00

## TODAY

In [13]:
today_date = dt.datetime.today().date()
today_row = df[df['Date'] == pd.to_datetime(today_date)]
today_row

,Date,One,Two,Three,Add,Minus,yt,screen,sleep_12,wake_8,Number,Weekday
1,2024-11-18,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1034,Monday

## CURRENT WEEK => FIRST WEEK

In [14]:
today_date = datetime.today().date()
start_of_week = today_date - timedelta(days=today_date.weekday())
end_of_week = start_of_week + timedelta(days=6)
start_of_week = pd.to_datetime(start_of_week)
end_of_week = pd.to_datetime(end_of_week)
current_week_rows = df[(df['Date'] >= start_of_week) & (df['Date'] <= end_of_week)]
current_week_rows

,Date,One,Two,Three,Add,Minus,yt,screen,sleep_12,wake_8,Number,Weekday
1,2024-11-18,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1034,Monday
2,2024-11-19,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1035,Tuesday
3,2024-11-20,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1036,Wednesday
4,2024-11-21,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1037,Thursday
5,2024-11-22,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1038,Friday
6,2024-11-23,Extra.py,Chill.py,Gym?.js,0,530,0.0,0.0,1.0,0.0,1039,Saturday
7,2024-11-24,Extra.py,Chill.py,GFGc?.js,0,210,0.0,0.0,1.0,0.0,1040,Sunday

## FOURTH WEEK

In [15]:
df.iloc[-7:]

,Date,One,Two,Three,Add,Minus,yt,screen,sleep_12,wake_8,Number,Weekday
22,2024-12-09,RecSys5,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1055,Monday
23,2024-12-10,ML.all,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1056,Tuesday
24,2024-12-11,Revision,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1057,Wednesday
25,2024-12-12,Revision,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1058,Thursday
26,2024-12-13,Revision,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1059,Friday
27,2024-12-14,Extra.py,Chill.py,Gym?.js,0,530,0.0,0.0,1.0,0.0,1060,Saturday
28,2024-12-15,Extra.py,Chill.py,GFGc?.js,0,530,0.0,0.0,1.0,0.0,1061,Sunday

## THIRD WEEK

In [16]:
df.iloc[-14:-7]

,Date,One,Two,Three,Add,Minus,yt,screen,sleep_12,wake_8,Number,Weekday
15,2024-12-02,Ts5,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1048,Monday
16,2024-12-03,RecSys1,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1049,Tuesday
17,2024-12-04,RecSys2,iOPEX.py,Gym?.js,0,8583,0.0,0.0,1.0,0.0,1050,Wednesday
18,2024-12-05,RecSys3,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1051,Thursday
19,2024-12-06,RecSys4,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1052,Friday
20,2024-12-07,Extra.py,Chill.py,Gym?.js,0,530,0.0,0.0,1.0,0.0,1053,Saturday
21,2024-12-08,Extra.py,Chill.py,GFGc?.js,0,210,0.0,0.0,1.0,0.0,1054,Sunday

## SECOND WEEK

In [17]:
df.iloc[-21:-14]

,Date,One,Two,Three,Add,Minus,yt,screen,sleep_12,wake_8,Number,Weekday
8,2024-11-25,Ts.intro,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1041,Monday
9,2024-11-26,Ts1,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1042,Tuesday
10,2024-11-27,Ts2,iOPEX.py,Gym?.js,20000,12750,0.0,0.0,1.0,0.0,1043,Wednesday
11,2024-11-28,Ts3,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1044,Thursday
12,2024-11-29,Ts4,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1045,Friday
13,2024-11-30,Extra.py,Chill.py,Gym?.js,32000,9530,0.0,0.0,1.0,0.0,1046,Saturday
14,2024-12-01,Extra.py,Chill.py,GFGc?.js,0,530,0.0,0.0,1.0,0.0,1047,Sunday

## FIRST WEEK

In [18]:
df.iloc[-28:-21]

,Date,One,Two,Three,Add,Minus,yt,screen,sleep_12,wake_8,Number,Weekday
1,2024-11-18,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1034,Monday
2,2024-11-19,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1035,Tuesday
3,2024-11-20,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1036,Wednesday
4,2024-11-21,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1037,Thursday
5,2024-11-22,Bc,iOPEX.py,Gym?.js,0,250,0.0,0.0,1.0,0.0,1038,Friday
6,2024-11-23,Extra.py,Chill.py,Gym?.js,0,530,0.0,0.0,1.0,0.0,1039,Saturday
7,2024-11-24,Extra.py,Chill.py,GFGc?.js,0,210,0.0,0.0,1.0,0.0,1040,Sunday